# Generated by Django 5.2 on 2025-11-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_ip', models.CharField(max_length=50, verbose_name='摄像头IP')),
                ('camera_user', models.CharField(max_length=50, verbose_name='用户名')),
                ('task_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='success', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='录制文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '录制日志',
                'verbose_name_plural': '录制日志',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='cameras_rec_start_t_3cb8e6_idx'), models.Index(fields=['camera_ip'], name='cameras_rec_camera__f436e7_idx'), models.Index(fields=['status'], name='cameras_rec_status_7ff838_idx')],
            },
        ),
    ]
