# Generated by Django 5.2.6 on 2025-11-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(verbose_name='帧序号')),
                ('timestamp', models.FloatField(verbose_name='视频时间戳(秒)')),
                ('image_path', models.CharField(max_length=500, verbose_name='截图路径')),
                ('confidence', models.FloatField(verbose_name='检测置信度')),
                ('bbox', models.JSONField(blank=True, null=True, verbose_name='边界框坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('record_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.recordlog', verbose_name='录制日志')),
            ],
            options={
                'verbose_name': '人物检测记录',
                'verbose_name_plural': '人物检测记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_log', 'timestamp'], name='cameras_per_record__40b9f9_idx'), models.Index(fields=['-created_at'], name='cameras_per_created_91af16_idx')],
            },
        ),
    ]
