# Generated by Django 5.2.6 on 2025-11-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_persondetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlog',
            name='analysis_status',
            field=models.CharField(choices=[('pending', '待检测'), ('processing', '检测中'), ('completed', '已完成'), ('failed', '检测失败')], default='pending', max_length=20, verbose_name='检测状态'),
        ),
        migrations.AddField(
            model_name='recordlog',
            name='analysis_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='检测完成时间'),
        ),
    ]
