# Generated by Django 5.2.6 on 2025-11-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_add_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetection',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述(英文)'),
        ),
        migrations.AddField(
            model_name='persondetection',
            name='caption_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='描述生成时间'),
        ),
        migrations.AddField(
            model_name='persondetection',
            name='caption_status',
            field=models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='描述生成状态'),
        ),
        migrations.AddField(
            model_name='persondetection',
            name='caption_zh',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述(中文)'),
        ),
        migrations.AddField(
            model_name='persondetection',
            name='keywords',
            field=models.JSONField(blank=True, null=True, verbose_name='关键词列表'),
        ),
        migrations.AddIndex(
            model_name='persondetection',
            index=models.Index(fields=['caption_status'], name='cameras_per_caption_f28dad_idx'),
        ),
    ]
