# Generated by Django 5.2.6 on 2025-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_persondetection_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
                ('gpu_utilization', models.FloatField(verbose_name='GPU利用率(%)')),
                ('memory_used', models.IntegerField(verbose_name='已用显存(MB)')),
                ('memory_total', models.IntegerField(verbose_name='总显存(MB)')),
                ('memory_percent', models.FloatField(verbose_name='显存使用率(%)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='GPU温度(°C)')),
                ('task_type', models.CharField(choices=[('idle', '空闲'), ('yolo', 'YOLOv8检测'), ('blip2', 'BLIP2描述生成'), ('other', '其他任务')], default='idle', max_length=50, verbose_name='任务类型')),
                ('worker_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Worker名称')),
                ('alert_level', models.CharField(choices=[('normal', '正常'), ('warning', '警告'), ('critical', '严重')], default='normal', max_length=20, verbose_name='告警级别')),
            ],
            options={
                'verbose_name': 'GPU监控记录',
                'verbose_name_plural': 'GPU监控记录',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='cameras_gpu_timesta_625984_idx'), models.Index(fields=['task_type'], name='cameras_gpu_task_ty_54c90f_idx'), models.Index(fields=['alert_level'], name='cameras_gpu_alert_l_b56613_idx')],
            },
        ),
    ]
