"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 根据环境加载不同的 .env 文件
# 优先从环境变量 DJANGO_ENV 读取，如果没有则默认为 'dev'
ENVIRONMENT = os.getenv('DJANGO_ENV', 'dev')

# 根据环境选择对应的 .env 文件
if ENVIRONMENT == 'prod':
    env_file = BASE_DIR / ".env.prod"
elif ENVIRONMENT == 'dev':
    env_file = BASE_DIR / ".env.dev"
else:
    # 默认加载 .env
    env_file = BASE_DIR / ".env"

# 加载环境变量文件
if env_file.exists():
    load_dotenv(env_file)
    print(f"Loaded environment from: {env_file}")
else:
    print(f"Warning: Environment file {env_file} not found!")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=)if-ey+owf(*eurzepjo&o2&4jvffi6=rex&ln38uqf$ykrsp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps',
    'apps.cameras'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.mysql',
      'NAME': os.getenv('DB_NAME', 'mycamera_db'),
      'USER': os.getenv('DB_USER', 'root'),
      'PASSWORD': os.getenv('DB_PASSWORD', ''),
      'HOST': os.getenv('DB_HOST', 'localhost'),
      'PORT': os.getenv('DB_PORT', '3306'),
      'OPTIONS': {
          'charset': 'utf8mb4',
          'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
      }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Redis 作为 Celery Broker
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')

# 可选：保存任务结果
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# 时区
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'Asia/Shanghai')
CELERY_ENABLE_UTC = True

# Celery 并发控制 - 限制视频分析任务的并发数
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 一次只取一个任务
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # 每个 worker 处理10个任务后重启（防止内存泄漏）

# 任务路由 - 视频分析任务使用专用队列
CELERY_TASK_ROUTES = {
    'apps.cameras.tasks.analyze_video_for_person': {
        'queue': 'video_analysis',
        'routing_key': 'video.analysis',
    },
    'apps.cameras.tasks.generate_captions_batch': {
        'queue': 'video_analysis',  # 和YOLO共用队列，避免并行冲突
        'routing_key': 'video.caption',
    },
}

CELERY_BEAT_SCHEDULE = {
    "record_camera_1": {
        "task": "apps.cameras.tasks.record_camera_task",
        "schedule": crontab(minute="*"),  # 每分钟执行一次
        "args": (
            os.getenv("CAMERA1_IP"),
            os.getenv("CAMERA1_USER"),
            os.getenv("CAMERA1_PASSWORD"),
            int(os.getenv("CAMERA1_PORT")),
            os.getenv("CAMERA1_PATH")
        ),
    },
    "record_camera_2": {
        "task": "apps.cameras.tasks.record_camera_task",
        "schedule": crontab(minute="*"),
        "args": (
            os.getenv("CAMERA2_IP"),
            os.getenv("CAMERA2_USER"),
            os.getenv("CAMERA2_PASSWORD"),
            int(os.getenv("CAMERA2_PORT")),
            os.getenv("CAMERA2_PATH")
        ),
    },
    # 批量生成图片描述 - 每10分钟执行一次
    "batch_generate_captions": {
        "task": "apps.cameras.tasks.generate_captions_batch",
        "schedule": crontab(minute="*/10"),  # 每10分钟执行一次
        "options": {
            "expires": 540,  # 任务9分钟后过期，避免堆积
        },
    },
}

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console_info': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',  # 输出到 stdout → .log 文件
            'formatter': 'verbose',
        },
        'console_error': {
            'level': 'WARNING',  # 只有 WARNING 以上才输出
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stderr',  # 输出到 stderr → .err 文件
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console_info', 'console_error'],
        'level': 'INFO',
    },
    'loggers': {
        'apps.cameras': {
            'handlers': ['console_info', 'console_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console_info', 'console_error'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}